name: Validation
permissions:
  contents: read
  packages: write
  checks: write

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # If your repository uses lfs include this property
        with:
          lfs: 'true'

      - name: Checkout Validation
        uses: actions/checkout@v4
        with:
          repository: dustiexx/capstone-private-test
          ref: 'main'
          path: 'validation'
          # Validation token defined in the usage instructions
          token: ${{ secrets.VALIDATION_TOKEN }}
      - name: Make Tiger executable
        run: |
          chmod +x validation/tiger/ck3-tiger
          chmod +x validation/tiger/vic3-tiger
          chmod +x validation/tiger/validate
      - name: Validate
        uses: ./validation/
        with:
          mod-directory: 'mod'
          action-directory: 'validation'
          update-tiger: 'true'
